# Generated by Django 4.2.6 on 2023-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0002_year_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='files',
        ),
        migrations.AddField(
            model_name='material',
            name='files',
            field=models.FileField(default='hi', upload_to='past_questions/'),
            preserve_default=False,
        ),
    ]
